defaults:
  - train_config
  - _self_
  #- override hydra/laucnher: submitit_local
  - override hydra/launcher: submitit_slurm

hydra:
    launcher:
        tasks_per_node: 1
        cpus_per_task: 10
        gpus_per_node: 1
        timeout_min: 1440
        mem_gb: 30


